[package]
name = "suggestion"
version = "0.1.0"
edition = "2021"
authors = ["Ken Matsui <26405363+ken-matsui@users.noreply.github.com>"]
description = "Provides suggestion traits for all collection types in the standard library"
license = "MIT"
readme = "README.md"
repository = "https://github.com/ken-matsui/suggestion/"
homepage = "https://github.com/ken-matsui/suggestion#readme"
documentation = "https://docs.rs/suggestion"

[dependencies]
lev_distance = "0.1.0"
