[package]
name = "ken-matsui/suggest"
version = "0.3.4"
description = "A CLI tool to provide similar name suggestions like \"Did you mean?\""
license = "MIT"
readme = "README.md"
repository = "https://github.com/ken-matsui/suggest"
homepage = "https://github.com/ken-matsui/suggest#readme"

[[module]]
name = "suggest"
source = "target/wasm32-wasi/release/suggest.wasm"
abi = "wasi"

[module.interfaces]
wasi = "0.1.0-unstable"

[[command]]
name = "suggest"
module = "suggest"
